In [1]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten,Embedding
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.preprocessing.text import text_to_word_sequence
from numpy import array

In [2]:
#전 처리할 텍스트 정하기
text = '해보지 않으면 해낼 수 없다'

#해당 텍스트 토큰화
result = text_to_word_sequence(text)
print("\n원문: \n", text)
print("\n토큰 화: \n", result)


원문: 
 해보지 않으면 해낼 수 없다

토큰 화: 
 ['해보지', '않으면', '해낼', '수', '없다']


In [3]:
# 전처리 하려는 세개의 문장 정하기
docs = ['먼저 텍스트의 각 단어를 나누어 토큰화 합니다.',
       '텍스트의 단어로 토큰화 해야 딥러닝에서 인식됩니다.',
       '토큰화 한 결과는 딥러닝에서 사용 할 수 있습니다.',
       ]

#토큰화 함수를 이용해 전처리 하는과정
token = Tokenizer() # 토큰화 함수 지정
token.fit_on_texts(docs) # 토큰화 함수에 문장 적용하기


In [4]:
#각 옵션에 맞춰 단어의 빈도ㄹ수를 계산한 결과 출력
print("\n단어 카운트 : ", token.word_counts)


단어 카운트 :  OrderedDict([('먼저', 1), ('텍스트의', 2), ('각', 1), ('단어를', 1), ('나누어', 1), ('토큰화', 3), ('합니다', 1), ('단어로', 1), ('해야', 1), ('딥러닝에서', 2), ('인식됩니다', 1), ('한', 1), ('결과는', 1), ('사용', 1), ('할', 1), ('수', 1), ('있습니다', 1)])


In [6]:
#출력 순서는 랜덤
print("\n문장 카운트 : ", token.document_count)
print("\n각 단어가 몇개의 문장에 포함되어 있는가 :\n ", token.word_docs)
print("\n각 단어에 매겨진 인덱스 값 : \n", token.word_index)


문장 카운트 :  3

각 단어가 몇개의 문장에 포함되어 있는가 :
  defaultdict(<class 'int'>, {'합니다': 1, '각': 1, '먼저': 1, '단어를': 1, '텍스트의': 2, '나누어': 1, '토큰화': 3, '단어로': 1, '해야': 1, '인식됩니다': 1, '딥러닝에서': 2, '수': 1, '있습니다': 1, '결과는': 1, '한': 1, '사용': 1, '할': 1})

각 단어에 매겨진 인덱스 값 : 
 {'토큰화': 1, '텍스트의': 2, '딥러닝에서': 3, '먼저': 4, '각': 5, '단어를': 6, '나누어': 7, '합니다': 8, '단어로': 9, '해야': 10, '인식됩니다': 11, '한': 12, '결과는': 13, '사용': 14, '할': 15, '수': 16, '있습니다': 17}


In [7]:
text = "오랫동안 꿈꾸는 이는 그 꿈을 닮아간다"

token = Tokenizer()
token.fit_on_texts([text])
print(token.word_index)

{'오랫동안': 1, '꿈꾸는': 2, '이는': 3, '그': 4, '꿈을': 5, '닮아간다': 6}


In [8]:
# 인덱스만 뽑아줌
x = token.texts_to_sequences([text])
print(x)

[[1, 2, 3, 4, 5, 6]]


In [9]:
from tensorflow.keras.utils import to_categorical

#원 핫 인코딩
word_size = len(token.word_index) +1
x = to_categorical(x, num_classes=word_size)

In [10]:
# 텍스트 리뷰 자료를 지정합니다.
docs = ["너무 재밌네요","최고예요","참 잘 만든 영화예요","추천하고 싶은 영화입니다","한번 더 보고싶네요",
        "글쎄요","별로예요","생각보다 지루하네요","연기가 어색해요","재미없어요"]

# 긍정리뷰는 1, 부정리뷰는 0으로 클래스를 지정합니다.
classes = array([1,1,1,1,1,0,0,0,0,0])

token = Tokenizer()
token.fit_on_texts(docs)
print(token.word_index)
x = token.texts_to_sequences(docs)
print("\n리뷰 텍스트, 토큰화 결과\n", x)


{'너무': 1, '재밌네요': 2, '최고예요': 3, '참': 4, '잘': 5, '만든': 6, '영화예요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한번': 11, '더': 12, '보고싶네요': 13, '글쎄요': 14, '별로예요': 15, '생각보다': 16, '지루하네요': 17, '연기가': 18, '어색해요': 19, '재미없어요': 20}

리뷰 텍스트, 토큰화 결과
 [[1, 2], [3], [4, 5, 6, 7], [8, 9, 10], [11, 12, 13], [14], [15], [16, 17], [18, 19], [20]]


In [11]:
# 학습을 하기위해선 데이터의 길이를 맞춰줘야한다.
padded_x = pad_sequences(x, 4)
print("\n 패딩 결과:\n ", padded_x)


 패딩 결과:
  [[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [ 0 11 12 13]
 [ 0  0  0 14]
 [ 0  0  0 15]
 [ 0  0 16 17]
 [ 0  0 18 19]
 [ 0  0  0 20]]


In [13]:
# 임베딩에 입력될 단어의 수를 지정합니다.
word_size = len(token.word_index) +1
model = Sequential()
model.add(Embedding(word_size, 8 , input_length=4))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(padded_x, classes, epochs=20)

print("\n Accuracy :%.4f" % (model.evaluate(padded_x, classes)[1]))

Train on 10 samples
Epoch 1/20
10/10 [==============================] - 4s 375ms/sample - loss: 0.6892 - accuracy: 0.6000
Epoch 2/20
10/10 [==============================] - 0s 469us/sample - loss: 0.6874 - accuracy: 0.6000
Epoch 3/20
10/10 [==============================] - 0s 736us/sample - loss: 0.6857 - accuracy: 0.7000
Epoch 4/20
10/10 [==============================] - 0s 609us/sample - loss: 0.6839 - accuracy: 0.7000
Epoch 5/20
10/10 [==============================] - 0s 662us/sample - loss: 0.6821 - accuracy: 0.8000
Epoch 6/20
10/10 [==============================] - 0s 492us/sample - loss: 0.6803 - accuracy: 0.9000
Epoch 7/20
10/10 [==============================] - 0s 565us/sample - loss: 0.6785 - accuracy: 0.9000
Epoch 8/20
10/10 [==============================] - 0s 483us/sample - loss: 0.6767 - accuracy: 0.9000
Epoch 9/20
10/10 [==============================] - 0s 615us/sample - loss: 0.6748 - accuracy: 0.9000
Epoch 10/20
10/10 [==============================] - 0s 699us/